steps:
# Krok 1: Sestavení kontejneru
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/playeranalysis/${REPO_NAME}:${COMMIT_SHA}', '.']

# Krok 2: Nahrání kontejneru do registru
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/playeranalysis/${REPO_NAME}:${COMMIT_SHA}']

# Krok 3: Nasazení do Cloud Run se všemi nastaveními
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'playeranalysis'
    - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/playeranalysis/${REPO_NAME}:${COMMIT_SHA}'
    - '--region=europe-west1'
    - '--cpu=2'
    - '--memory=4Gi'
    - '--timeout=600s'
    - '--update-secrets=GCP_SERVICE_ACCOUNT_JSON. =gemini-api-key:latest'
    - '--allow-unauthenticated'

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/playeranalysis/${REPO_NAME}:${COMMIT_SHA}'
