steps:
# Krok 1: Sestavení Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/football/${REPO_NAME}:${COMMIT_SHA}', '.']

# Krok 2: Nahrání image do Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/football/${REPO_NAME}:${COMMIT_SHA}']

# Krok 3: Nasazení nové verze na Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      gcloud run deploy football \
        --image=europe-west1-docker.pkg.dev/$PROJECT_ID/football/${REPO_NAME}:${COMMIT_SHA} \
        --region=europe-west1 \
        --cpu=4 \
        --memory=4Gi \
        --timeout=600s \
        --execution-environment=gen2 \
        --update-secrets=GCP_SA_JSON=gemini-api-key:latest \
        --min-instances=1 \
        --allow-unauthenticated

# Seznam vytvořených imagů
images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/football/${REPO_NAME}:${COMMIT_SHA}'

# Nastavení logování
options:
  logging: CLOUD_LOGGING_ONLY
